### ISSUE TITLE
群晖设备无法创建沙盒容器

### ISSUE THREAD

**Issue by Asukaaa648** [KroMiose/nekro-agent#7]
通过docker compose部署的nekro-agent
群晖系统

解析程式回复：等待执行资源
设置共享目录权限：/volume4/EXT4/nekro_agent/sandboxes/sandbox_private_2150757481 777
卡在这一步不动了

容器已经给予root权限，所有操作都是root状态下运行的。
![image](https://github.com/user-attachments/assets/2761763f-a566-4ed3-abf9-ff59ab38860b)
同时容器启动一段时间后变成警告状态，DEBUG日志并未报错

**Comment by Asukaaa648** [comment]
![image](https://github.com/user-attachments/assets/00ba647e-7888-4588-8d77-a21d9321ffbc)
事实上对权限的修改已经完成了，可是未能运行下一步

**Comment by Asukaaa648** [comment]
我添加了些许调试日志
![image](https://github.com/user-attachments/assets/0e0c1401-e154-47b5-ac2b-394f53d006da)
![image](https://github.com/user-attachments/assets/3cb20e6c-7222-4f09-bc42-be1023edaba0)
证明是在运行container: DockerContainer = await docker.containers.run时卡住的

**Comment by Asukaaa648** [comment]
我添加了try语句，发现了问题：
DockerError(400,'NanoCPUs can not be set,as your kernel does not support CPU CFS scheduler or the cgroup is not mounted')

**Comment by Asukaaa648** [comment]
将NanoCPUs一行替换为
"CpuShares": 512
即可解决问题

但是又出现了新的问题：uploads目录下没有文件
Bind mount failed:'/volume4/EXT4/nekro_agent/uploads/group_923248932'does not exists

**Comment by Asukaaa648** [comment]
已解决，手动添加目录即可

**Comment by Asukaaa648** [comment]
但是容器一直为不健康状态是什么原因？应当修复

**Comment by KroMiose** [comment]
除了容器不健康以外，是否有其他异常现象？
