### ISSUE TITLE
token用量问题

### ISSUE THREAD

**Issue by padoru233** [KroMiose/nekro-agent#8]
使用1panel手动搭建，协议端napcat-docker
第三方转发，每次调用都要至少3000token，也就是2000-3000字符？人设才几十个字，加上上下文也远远到不了，希望能解释一下消耗过程
![IMG_20241225_192429](https://github.com/user-attachments/assets/b597d278-d820-4cf8-9a59-ff4ae240b6ee)

**Comment by KroMiose** [comment]
中文每个汉字约占2-3token，并且na有包括行为控制、扩展方法、环境信息等提示词需要参与上下文，这个token消耗是合理的，有兴趣可以阅读源码详细了解
